//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataListen.srCouponPrint {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srCouponPrint.wsCouponPrintSoap")]
    public interface wsCouponPrintSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCouponData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCouponData(string strSiteCode, string strState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCouponState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateCouponState(string strCouponID, string strState);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsCouponPrintSoapChannel : DataListen.srCouponPrint.wsCouponPrintSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsCouponPrintSoapClient : System.ServiceModel.ClientBase<DataListen.srCouponPrint.wsCouponPrintSoap>, DataListen.srCouponPrint.wsCouponPrintSoap {
        
        public wsCouponPrintSoapClient() {
        }
        
        public wsCouponPrintSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsCouponPrintSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCouponPrintSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCouponPrintSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetCouponData(string strSiteCode, string strState) {
            return base.Channel.GetCouponData(strSiteCode, strState);
        }
        
        public bool UpdateCouponState(string strCouponID, string strState) {
            return base.Channel.UpdateCouponState(strCouponID, strState);
        }
    }
}
