//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozart.SecHandProductTip {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecHandProductTip.SecHandProductMsgSoap")]
    public interface SecHandProductMsgSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SecHandProductTipResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecHandProductTip", ReplyAction="*")]
        Mozart.SecHandProductTip.SecHandProductTipResponse SecHandProductTip(Mozart.SecHandProductTip.SecHandProductTipRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SecHandProductTipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SecHandProductTip", Namespace="http://tempuri.org/", Order=0)]
        public Mozart.SecHandProductTip.SecHandProductTipRequestBody Body;
        
        public SecHandProductTipRequest() {
        }
        
        public SecHandProductTipRequest(Mozart.SecHandProductTip.SecHandProductTipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SecHandProductTipRequestBody {
        
        public SecHandProductTipRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SecHandProductTipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SecHandProductTipResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mozart.SecHandProductTip.SecHandProductTipResponseBody Body;
        
        public SecHandProductTipResponse() {
        }
        
        public SecHandProductTipResponse(Mozart.SecHandProductTip.SecHandProductTipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SecHandProductTipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SecHandProductTipResult;
        
        public SecHandProductTipResponseBody() {
        }
        
        public SecHandProductTipResponseBody(string SecHandProductTipResult) {
            this.SecHandProductTipResult = SecHandProductTipResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecHandProductMsgSoapChannel : Mozart.SecHandProductTip.SecHandProductMsgSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecHandProductMsgSoapClient : System.ServiceModel.ClientBase<Mozart.SecHandProductTip.SecHandProductMsgSoap>, Mozart.SecHandProductTip.SecHandProductMsgSoap {
        
        public SecHandProductMsgSoapClient() {
        }
        
        public SecHandProductMsgSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecHandProductMsgSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecHandProductMsgSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecHandProductMsgSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mozart.SecHandProductTip.SecHandProductTipResponse Mozart.SecHandProductTip.SecHandProductMsgSoap.SecHandProductTip(Mozart.SecHandProductTip.SecHandProductTipRequest request) {
            return base.Channel.SecHandProductTip(request);
        }
        
        public string SecHandProductTip() {
            Mozart.SecHandProductTip.SecHandProductTipRequest inValue = new Mozart.SecHandProductTip.SecHandProductTipRequest();
            inValue.Body = new Mozart.SecHandProductTip.SecHandProductTipRequestBody();
            Mozart.SecHandProductTip.SecHandProductTipResponse retVal = ((Mozart.SecHandProductTip.SecHandProductMsgSoap)(this)).SecHandProductTip(inValue);
            return retVal.Body.SecHandProductTipResult;
        }
    }
}
